### ISSUE TITLE
DummyDroid does no longer work

### ISSUE THREAD

**Issue by Kantaris** [onyxbits/dummydroid#4]
I tried it a few weeks ago and then it was possible to register a device and get a GSF ID but that's not possible anymore.

Error shown:

com.akdeniz.googleplaycrawler.GooglePlayException: Error=UNKNOWN_ERR

**Comment by therealssj** [comment]
The chance of dummydroid working is very low
You have to keep trying and it magically works

**Comment by onyxbits** [comment]
DummyDroid is currently broken and will remain broken for the foreseable
future till I find the time to rewrite it (see
http://blog.onyxbits.de/raccoon-v3-5-and-dummydroid-no-longer-working-241/ )

Am Montag, den 30.05.2016, 12:21 -0700 schrieb therealssj:

**Comment by tbcx** [comment]
EDIT:  Well, no sooner had I posted this, than I got both to work.  Not having been a fan of Google for a good long while, such inconsistencies don't really improve my opinion.

I realise this is old, but I was able to use DummyDroid successfully yesterday to produce a GSF ID.  Today, it no longer works.  Additionally I was able yesterday to use android-checkin-1.0.jar to produce a GSF ID;  today, that, too, no longer works.  I wonder if that is indicative of Google having changed something overnight?

DummyDroid error output:
com.akdeniz.googleplaycrawler.GooglePlayException: Error=UNKNOWN_ERR
android-checkin-1.0.jar error output:
Fetching auth (google service)...
Error=UNKNOWN_ERR
java.io.IOException: Can't find Auth // HTTP/1.1 404 Not Found
        at com.android.checkin.Checkin.postFormFetchValue(Checkin.java:108)
        at com.android.checkin.Checkin.fetchAuthGsf(Checkin.java:77)
        at com.android.checkin.Checkin.checkin(Checkin.java:54)
        at com.android.checkin.Main.main(Main.java:17)

**Comment by eighthave** [comment]
Maybe this would be fixed by this https://github.com/onyxbits/raccoon4/commit/0c2196be000bed01c8c0c8c72e955355aa9bf80d
